// Movies database
var movies = [{
  'title': 'Fanaa',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=Bd6Z2K5Ye28',
  'stars': '4',
},
{
  'title': 'Raees',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'My name is Khan',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=JEpqz33vKus',
  'stars': '4',
},
{
  'title': 'Idiots',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'Dilwale Dulhania Le Jayenge',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=c25GKl5VNeY',
  'stars': '4',
},
{
  'title': 'Veer-Zaara',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=OSaVImLnnsw',
  'stars': '4',
},
{'title': 'Jab Tak Hai Jaan',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=6Mp-7kM3Uqg',
  'stars': '5',
},
{ 'title': 'Kites',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=rezNHSKgDH0&t=39s',
  'stars': '5',
},
{ 'title': 'Happy new year',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=JGHwANkQFrg',
  'stars': '4',
},
{'title': 'Devdas',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=8tuHQWGMQwY',
  'stars': '4',
},
{ 'title': 'Guzaarish',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=bZ0Ge2K7vIs',
  'stars': '4',
},
{ 'title': 'Dear zindagi',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=5DkO7ksXY8E',
  'stars': '5',
},
{'title': 'Jagga jasoos',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=xtm48kJwL1I',
  'stars': '5',
},
{'title': 'Go Goa Gone',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=4V5zGNVRmaE',
  'stars': '3',
},
{'title': 'Kung fu yoga',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=2Ex_kBrofOY',
  'stars': '3',
},
{ 'title': 'Don 2',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=_X5w-6PqoZ0',
  'stars': '5',
},
{'title': 'Commando 2',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=gO4ZIgHOR50',
  'stars': '4',
},
{'title': 'krrish',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=6oxkN1rRPW4',
  'stars': '4',
},
{'title': 'Dil Ka Rishta',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=ubWrh3AWbWo',
  'stars': '4',
},
{'title': 'Chori Chori Chupke Chupke',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=fevmvfW72_8',
  'stars': '5',
},

];