// Movies database
var movies = [{
  'title': 'fanaa',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=Bd6Z2K5Ye28',
  'stars': '4',
},
{
  'title': 'raees',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'my name is khan',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=JEpqz33vKus',
  'stars': '4',
},
{
  'title': 'mohabbatein',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=JEpqz33vKus',
  'stars': '4',
},
{
  'title': '3 idiots',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'Munna bhai m.b.b.s.',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'singham',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'om shanti om',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'rang de basanti',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'ek tha tiger',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'hulchul',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'kuch kuch hota hai',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=K0eDlFX9GMc',
  'stars': '4',
},
{
  'title': 'dilwale dulhania le jayenge',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=c25GKl5VNeY',
  'stars': '4',
},
{
  'title': 'kabhi khushi kabhie gham',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=c25GKl5VNeY',
  'stars': '4',
},
{
  'title': 'kal ho naa ho',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=c25GKl5VNeY',
  'stars': '4',
},
{
  'title': 'veer-zaara',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=OSaVImLnnsw',
  'stars': '4',
},
{'title': 'jab tak hai jaan',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=6Mp-7kM3Uqg',
  'stars': '5',
},
{ 'title': 'kites',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=rezNHSKgDH0&t=39s',
  'stars': '5',
},
{ 'title': 'happy new year',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=JGHwANkQFrg',
  'stars': '4',
},
{'title': 'devdas',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=8tuHQWGMQwY',
  'stars': '4',
},
{ 'title': 'guzaarish',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=bZ0Ge2K7vIs',
  'stars': '4',
},
{ 'title': 'dear zindagi',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=5DkO7ksXY8E',
  'stars': '5',
},
{'title': 'jagga jasoos',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=xtm48kJwL1I',
  'stars': '5',
},
{'title': 'go goa gone',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=4V5zGNVRmaE',
  'stars': '3',
},
{'title': 'kung fu yoga',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=2Ex_kBrofOY',
  'stars': '3',
},
{ 'title': 'don 2',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=_X5w-6PqoZ0',
  'stars': '5',
},
{'title': 'commando 2',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=gO4ZIgHOR50',
  'stars': '4',
},
{'title': 'krrish',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=6oxkN1rRPW4',
  'stars': '4',
},
{'title': 'dil ka rishta',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=ubWrh3AWbWo',
  'stars': '4',
},
{'title': 'chori chori chupke chupke',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=fevmvfW72_8',
  'stars': '5',
},
{
  'title': 'kabhi alvida naa kehna',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'vanaja',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'desi kattey',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'shivaay',
  'genre': 'Action',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},

{
  'title': 'baghban',
  'genre': 'Drama',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'Half Girlfriend',
  'genre': 'Romance',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},

{
  'title': 'rab ne bana di jodi',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'phillauri',
  'genre': 'Estrenos',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'zindagi na milegi dobara',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'jab harry met sejal',
  'genre': 'Estrenos',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'mujhse dosti karoge!',
  'genre': 'Musical',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},
{
  'title': 'chennai express',
  'genre': 'Comedy',
  'trailer': 'https://www.youtube.com/watch?v=8iv3ksZs0hk',
  'stars': '3',
},

];